name: Square Light Studio
favicon: null
layout_spectrum: 0.24663
typography_spectrum: 0.63231
title: 'Wedding Photography, Event Photography, Birthdays, Debuts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1000'
    - '#dcdde1'
    - '#7b6554'
    - '#b4afab'
    - '#533013'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0
purpose: []
