name: SquareLightStudio
favicon: null
layout_spectrum: 0.021343980450183153
typography_spectrum: 0.8808631224092096
title: 'Wedding Photography, Event Photography, Birthdays, Debuts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9004009284544736
  lightness: 0.2852989500388503
  saturation: 0.09094375348649919
  rhythmicContrast: 0.7696543587371707
purpose: []
