name: SquareLightStudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63231
title: 'Wedding Photography, Event Photography, Birthdays, Debuts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdf8f4'
    - '#eca40b'
    - '#c22d29'
    - '#211300'
    - '#b2754a'
  brandStrength: 0.125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
