name: Square Light Studio
favicon: null
layout_spectrum: 0
typography_spectrum: 0.63231
title: 'Wedding Photography, Event Photography, Birthdays, Debuts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8eade'
    - '#b5a7a0'
    - '#1d191a'
    - '#a86742'
    - '#514850'
  brandStrength: 1
  lightness: 1
  saturation: 1
  rhythmicContrast: 1
purpose: []
