name: Square Light Studio
favicon: null
layout_spectrum: 1
typography_spectrum: 0.63231
title: 'Wedding Photography, Event Photography, Birthdays, Debuts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeff'
    - '#474e00'
    - '#f90000'
    - '#a2d800'
    - '#6492fd'
  brandStrength: 0
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0
purpose: []
